<?php
/**
 * Created by PhpStorm.
 * User: opitz
 * Date: 10/08/18
 * Time: 16:04
 */

require_once('../../config.php');
include_once ('../../course/lib.php');
include_once ('../../course/modlib.php');

global $CFG, $DB;
$doit = 1;

function add_qsection($course, $doit) {
    $numsections = course_get_format($course)->get_last_section_number();
    return course_create_section($course->id, $numsections+1, true);
}

function add_qreview($course, $qsection) {
    global $DB;

    // check for a Q-Review module already existing for this course
    $sql = "select cm.*
from {course_modules} cm
join {modules} m on m.id = cm.module and m.name = 'lti'
join {lti} l on l.id = cm.instance
join {lti_types} lt on lt.id = l.typeid
where lt.tooldomain = 'echo360.org.uk'
and cm.course = $course->id
";
//    $qrecords = $DB->get_records_sql($sql);
//    $qrecord = array_shift($qrecords);
//    $test = 12;
    // check if there is already a Q-Review module present for the course - if so use it
    if($qrecords = $DB->get_records_sql($sql)) {
        $qrecord = array_shift($qrecords);
        return $qrecord->id;
    }

    $templatesettings = array(
        'name' => 'Q-Review Autogenerated',
        'introeditor' =>
            array(
                'text' => 'Autogenerated ...',
                'format' => '1',
            ),
        'showdescription' => '0',
        'showtitlelaunch' => '1',
        'typeid' => 94,
        'urlmatchedtypeid' => 94,
        'launchcontainer' => '1',
        'instructorcustomparameters' => '',
        'instructorchoicesendname' => '0',
        'instructorchoicesendemailaddr' => '0',
        'instructorchoiceacceptgrades' => '0',
        'grade_rescalegrades' => NULL,
        'gradepass' => NULL,
        'visible' => 1,
        'visibleoncoursepage' => 1,
        'cmidnumber' => '',
        'availabilityconditionsjson' => '{"op":"&","c":[],"showc":[]}',
        'tags' => '',
        'course' => $course->id, //null
        'section' => $qsection->section,  //null
        'module' => 21,  //null
        'modulename' => 'lti', //null
        'add' => 'lti', //null
        'update' => 0,
        'return' => 0,
        'sr' => 0,
        'competency_rule' => '0',
        'submitbutton2' => 'Save and return to course',
    );

    $result = add_moduleinfo((object) $templatesettings, $course);
    return $result->coursemodule;
}

function insert_result($section, $qmid) {
    global $DB;
    echo('insert_result here!');
    $comment = "A coment placeholder. Please edit using the topic edit command.";
    $iframe = "<iframe id='contentframe' height='600px' width='100%' src='../mod/lti/launch.php?id=$qmid&amp;triggerview=0' webkitallowfullscreen='' mozallowfullscreen='' allowfullscreen='' style='height: 685px;'></iframe>";

    $section = $DB->get_record('course_sections', array('id' => $section->id));
    $section->name = get_string('section_name', 'local_qsection');
    $section->summary = $comment.'<hr>'.$iframe;
//    $section->summary = $comment;
    $DB->update_record('course_sections', $section);
}

function insert_result0($section, $result) {
    global $DB;
    echo('insert_result here!');
    $comment = "A coment placeholder. Please edit using the topic edit command.";
    $iframe = "<iframe id='contentframe' height='600px' width='100%' src='../mod/lti/launch.php?id=$result->coursemodule&amp;triggerview=0' webkitallowfullscreen='' mozallowfullscreen='' allowfullscreen='' style='height: 685px;'></iframe>";

    $section = $DB->get_record('course_sections', array('id' => $section->id));
    $section->name = get_string('section_name', 'local_qsection');
    $section->summary = $comment.'<hr>'.$iframe;
//    $section->summary = $comment;
    $DB->update_record('course_sections', $section);
}

//======================================================================================================================
$courseid = $_REQUEST['courseid'];
$course = $DB->get_record('course', array('id' => $courseid), '*', MUST_EXIST);

// add a new "Q-Review" section to the course
$qsection = add_qsection($course, $doit);

// add Q-Review to qsection
$result = add_qreview($course, $qsection);

// insert Q-Reviev result as qsection summary
insert_result($qsection, $result);

// purge the cache and reload the course page
rebuild_course_cache($course->id);
$courseurl = course_get_url($course, $sectioninfo->section - 1, array('sr' => $sectionreturn));
redirect($courseurl);
